version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robinhood
    environment:
      DB_HOST: db
      DB_USER: robinhooduser
      DB_PASSWORD: robinhoodpassword
      DB_NAME: robinhood
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: robinhood
      MYSQL_USER: robinhooduser
      MYSQL_PASSWORD: robinhoodpassword
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db_data: